# Generated by Django 3.1.2 on 2022-04-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterForm',
        ),
    ]
